# Sync các ConstraintTemplate + Constraint từ folder gatekeeper/
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://github.com/Auzema/nguyendkhanhhung-aws-accelerator-p2.git
    path: intern/cloud/w10/lab/hung_lab/gatekeeper
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - ServerSideApply=true
